.TH pinta 1 "June 2010" "The Pinta Project" "Pinta"
.SH NAME
Pinta \- simple image editor
.SH SYNOPSIS
.B pinta
.I [<file_name>]
.SH DESCRIPTION
Pinta is a drawing/editing program modeled on Paint.NET. Its goal is to provide
a simplified alternative to the GIMP for casual users.
.PP
Features include:
.PP
 - Adjustments (Auto level, Black and White, Sepia, …)
 - Multiple layers
 - Unlimited undo/redo
 - Drawing tools (Paintbrush, Pencil, Shapes, …)
.PP
Pinta is currently early in development, and should be treated as such.
.SH OPTIONS
.TP
.B file_name
Optional. The name of the image file for Pinta to open.
.SH AUTHOR
Pinta is developed by the Pinta project contributors, led by Jonathan Pobst
<monkey@jpobst.com>. For a complete list of contributors, refer to the
\fBAbout\fR option in the \fBHelp\fR menu.
.SH BUGS
Pinta uses the Launchpad project to track bugs. Please submit bugs to
\fBhttps://bugs.edge.launchpad.net/pinta\fR.
