//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinta {
    
    
    public partial class ColorGradientWidget {
        
        private Gtk.EventBox eventbox;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Pinta.ColorGradientWidget
            Stetic.BinContainer.Attach(this);
            this.CanFocus = true;
            this.Events = ((Gdk.EventMask)(1534));
            this.Name = "Pinta.ColorGradientWidget";
            // Container child Pinta.ColorGradientWidget.Gtk.Container+ContainerChild
            this.eventbox = new Gtk.EventBox();
            this.eventbox.Events = ((Gdk.EventMask)(790));
            this.eventbox.Name = "eventbox";
            this.eventbox.VisibleWindow = false;
            this.Add(this.eventbox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
