// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Pinta {
    
    
    public partial class HueSaturationDialog {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label2;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.HBox hbox2;
        
        private Gtk.HScale hscaleHue;
        
        private Gtk.SpinButton spinHue;
        
        private Gtk.Button buttonHue;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label3;
        
        private Gtk.HSeparator hseparator3;
        
        private Gtk.HBox hbox4;
        
        private Gtk.HScale hscaleSaturation;
        
        private Gtk.SpinButton spinSaturation;
        
        private Gtk.Button buttonSaturation;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Label label4;
        
        private Gtk.HSeparator hseparator4;
        
        private Gtk.HBox hbox6;
        
        private Gtk.HScale hscaleLightness;
        
        private Gtk.SpinButton spinLightness;
        
        private Gtk.Button buttonLightness;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Pinta.HueSaturationDialog
            this.Name = "Pinta.HueSaturationDialog";
            this.Title = Mono.Unix.Catalog.GetString("Hue / Saturation");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.SkipTaskbarHint = true;
            // Internal child Pinta.HueSaturationDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Hue");
            this.hbox1.Add(this.label2);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.label2]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.hbox1.Add(this.hseparator2);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.hseparator2]));
            w3.Position = 1;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.hscaleHue = new Gtk.HScale(null);
            this.hscaleHue.CanFocus = true;
            this.hscaleHue.Name = "hscaleHue";
            this.hscaleHue.Adjustment.Lower = -180;
            this.hscaleHue.Adjustment.Upper = 180;
            this.hscaleHue.Adjustment.PageIncrement = 10;
            this.hscaleHue.Adjustment.StepIncrement = 1;
            this.hscaleHue.Adjustment.Value = 10;
            this.hscaleHue.DrawValue = false;
            this.hscaleHue.Digits = 0;
            this.hscaleHue.ValuePos = ((Gtk.PositionType)(2));
            this.hbox2.Add(this.hscaleHue);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.hscaleHue]));
            w5.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.spinHue = new Gtk.SpinButton(-180, 180, 1);
            this.spinHue.CanFocus = true;
            this.spinHue.Name = "spinHue";
            this.spinHue.Adjustment.PageIncrement = 10;
            this.spinHue.ClimbRate = 1;
            this.spinHue.Numeric = true;
            this.hbox2.Add(this.spinHue);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.spinHue]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.buttonHue = new Gtk.Button();
            this.buttonHue.CanFocus = true;
            this.buttonHue.Name = "buttonHue";
            this.buttonHue.UseUnderline = true;
            // Container child buttonHue.Gtk.Container+ContainerChild
            Gtk.Alignment w7 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w8 = new Gtk.HBox();
            w8.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w9 = new Gtk.Image();
            w9.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-back", Gtk.IconSize.Menu, 16);
            w8.Add(w9);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w11 = new Gtk.Label();
            w8.Add(w11);
            w7.Add(w8);
            this.buttonHue.Add(w7);
            this.hbox2.Add(this.buttonHue);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox2[this.buttonHue]));
            w15.Position = 2;
            w15.Expand = false;
            w15.Fill = false;
            this.vbox2.Add(this.hbox2);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Saturation");
            this.hbox3.Add(this.label3);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox3[this.label3]));
            w17.Position = 0;
            w17.Expand = false;
            w17.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.hseparator3 = new Gtk.HSeparator();
            this.hseparator3.Name = "hseparator3";
            this.hbox3.Add(this.hseparator3);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox3[this.hseparator3]));
            w18.Position = 1;
            this.vbox2.Add(this.hbox3);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
            w19.Position = 2;
            w19.Expand = false;
            w19.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.hscaleSaturation = new Gtk.HScale(null);
            this.hscaleSaturation.CanFocus = true;
            this.hscaleSaturation.Name = "hscaleSaturation";
            this.hscaleSaturation.Adjustment.Upper = 200;
            this.hscaleSaturation.Adjustment.PageIncrement = 10;
            this.hscaleSaturation.Adjustment.StepIncrement = 1;
            this.hscaleSaturation.Adjustment.Value = 100;
            this.hscaleSaturation.DrawValue = false;
            this.hscaleSaturation.Digits = 0;
            this.hscaleSaturation.ValuePos = ((Gtk.PositionType)(2));
            this.hbox4.Add(this.hscaleSaturation);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox4[this.hscaleSaturation]));
            w20.Position = 0;
            // Container child hbox4.Gtk.Box+BoxChild
            this.spinSaturation = new Gtk.SpinButton(0, 200, 1);
            this.spinSaturation.CanFocus = true;
            this.spinSaturation.Name = "spinSaturation";
            this.spinSaturation.Adjustment.PageIncrement = 10;
            this.spinSaturation.ClimbRate = 1;
            this.spinSaturation.Numeric = true;
            this.hbox4.Add(this.spinSaturation);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox4[this.spinSaturation]));
            w21.Position = 1;
            w21.Expand = false;
            w21.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.buttonSaturation = new Gtk.Button();
            this.buttonSaturation.CanFocus = true;
            this.buttonSaturation.Name = "buttonSaturation";
            this.buttonSaturation.UseUnderline = true;
            // Container child buttonSaturation.Gtk.Container+ContainerChild
            Gtk.Alignment w22 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w23 = new Gtk.HBox();
            w23.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w24 = new Gtk.Image();
            w24.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-back", Gtk.IconSize.Menu, 16);
            w23.Add(w24);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w26 = new Gtk.Label();
            w23.Add(w26);
            w22.Add(w23);
            this.buttonSaturation.Add(w22);
            this.hbox4.Add(this.buttonSaturation);
            Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.hbox4[this.buttonSaturation]));
            w30.Position = 2;
            w30.Expand = false;
            w30.Fill = false;
            this.vbox2.Add(this.hbox4);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
            w31.Position = 3;
            w31.Expand = false;
            w31.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            this.hbox5.Spacing = 6;
            // Container child hbox5.Gtk.Box+BoxChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Lightness");
            this.hbox5.Add(this.label4);
            Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.hbox5[this.label4]));
            w32.Position = 0;
            w32.Expand = false;
            w32.Fill = false;
            // Container child hbox5.Gtk.Box+BoxChild
            this.hseparator4 = new Gtk.HSeparator();
            this.hseparator4.Name = "hseparator4";
            this.hbox5.Add(this.hseparator4);
            Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.hbox5[this.hseparator4]));
            w33.Position = 1;
            this.vbox2.Add(this.hbox5);
            Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
            w34.Position = 4;
            w34.Expand = false;
            w34.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.hscaleLightness = new Gtk.HScale(null);
            this.hscaleLightness.CanFocus = true;
            this.hscaleLightness.Name = "hscaleLightness";
            this.hscaleLightness.Adjustment.Lower = -100;
            this.hscaleLightness.Adjustment.Upper = 100;
            this.hscaleLightness.Adjustment.PageIncrement = 10;
            this.hscaleLightness.Adjustment.StepIncrement = 1;
            this.hscaleLightness.DrawValue = false;
            this.hscaleLightness.Digits = 0;
            this.hscaleLightness.ValuePos = ((Gtk.PositionType)(2));
            this.hbox6.Add(this.hscaleLightness);
            Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox6[this.hscaleLightness]));
            w35.Position = 0;
            // Container child hbox6.Gtk.Box+BoxChild
            this.spinLightness = new Gtk.SpinButton(-100, 100, 1);
            this.spinLightness.CanFocus = true;
            this.spinLightness.Name = "spinLightness";
            this.spinLightness.Adjustment.PageIncrement = 10;
            this.spinLightness.ClimbRate = 1;
            this.spinLightness.Numeric = true;
            this.hbox6.Add(this.spinLightness);
            Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.hbox6[this.spinLightness]));
            w36.Position = 1;
            w36.Expand = false;
            w36.Fill = false;
            // Container child hbox6.Gtk.Box+BoxChild
            this.buttonLightness = new Gtk.Button();
            this.buttonLightness.CanFocus = true;
            this.buttonLightness.Name = "buttonLightness";
            this.buttonLightness.UseUnderline = true;
            // Container child buttonLightness.Gtk.Container+ContainerChild
            Gtk.Alignment w37 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w38 = new Gtk.HBox();
            w38.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w39 = new Gtk.Image();
            w39.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-back", Gtk.IconSize.Menu, 16);
            w38.Add(w39);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w41 = new Gtk.Label();
            w38.Add(w41);
            w37.Add(w38);
            this.buttonLightness.Add(w37);
            this.hbox6.Add(this.buttonLightness);
            Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.hbox6[this.buttonLightness]));
            w45.Position = 2;
            w45.Expand = false;
            w45.Fill = false;
            this.vbox2.Add(this.hbox6);
            Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox6]));
            w46.Position = 5;
            w46.Expand = false;
            w46.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w47.Position = 0;
            w47.Expand = false;
            w47.Fill = false;
            // Internal child Pinta.HueSaturationDialog.ActionArea
            Gtk.HButtonBox w48 = this.ActionArea;
            w48.Name = "dialog1_ActionArea";
            w48.Spacing = 10;
            w48.BorderWidth = ((uint)(5));
            w48.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w49 = ((Gtk.ButtonBox.ButtonBoxChild)(w48[this.buttonCancel]));
            w49.Expand = false;
            w49.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w50 = ((Gtk.ButtonBox.ButtonBoxChild)(w48[this.buttonOk]));
            w50.Position = 1;
            w50.Expand = false;
            w50.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 402;
            this.DefaultHeight = 235;
            this.Show();
        }
    }
}
