// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Pinta {
    
    
    public partial class HistogramWidget {
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Pinta.HistogramWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Pinta.HistogramWidget";
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
