// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Pinta {
    
    
    public partial class BrightnessContrastDialog {
        
        private Gtk.VBox vbox2;
        
        private Pinta.HScaleSpinButtonWidget hscalespinBrightness;
        
        private Pinta.HScaleSpinButtonWidget hscalespinContrast;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Pinta.BrightnessContrastDialog
            this.Name = "Pinta.BrightnessContrastDialog";
            this.Title = Mono.Unix.Catalog.GetString("Brightness / Contrast");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Internal child Pinta.BrightnessContrastDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hscalespinBrightness = new Pinta.HScaleSpinButtonWidget();
            this.hscalespinBrightness.Events = ((Gdk.EventMask)(256));
            this.hscalespinBrightness.Name = "hscalespinBrightness";
            this.hscalespinBrightness.Label = "Brightness";
            this.hscalespinBrightness.DefaultValue = 0;
            this.hscalespinBrightness.MaximumValue = 100;
            this.hscalespinBrightness.MinimumValue = -100;
            this.hscalespinBrightness.Value = 0;
            this.vbox2.Add(this.hscalespinBrightness);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.hscalespinBrightness]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hscalespinContrast = new Pinta.HScaleSpinButtonWidget();
            this.hscalespinContrast.Events = ((Gdk.EventMask)(256));
            this.hscalespinContrast.Name = "hscalespinContrast";
            this.hscalespinContrast.Label = "Contrast";
            this.hscalespinContrast.DefaultValue = 0;
            this.hscalespinContrast.MaximumValue = 100;
            this.hscalespinContrast.MinimumValue = -100;
            this.hscalespinContrast.Value = 0;
            this.vbox2.Add(this.hscalespinContrast);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.hscalespinContrast]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w4.Position = 0;
            // Internal child Pinta.BrightnessContrastDialog.ActionArea
            Gtk.HButtonBox w5 = this.ActionArea;
            w5.Name = "dialog1_ActionArea";
            w5.Spacing = 10;
            w5.BorderWidth = ((uint)(5));
            w5.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w6 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonCancel]));
            w6.Expand = false;
            w6.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonOk]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 394;
            this.DefaultHeight = 219;
            this.Show();
        }
    }
}
