// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Pinta {
    
    
    public partial class PosterizeDialog {
        
        private Gtk.VBox vbox2;
        
        private Pinta.HScaleSpinButtonWidget hscalespinRed;
        
        private Pinta.HScaleSpinButtonWidget hscalespinGreen;
        
        private Pinta.HScaleSpinButtonWidget hscalespinBlue;
        
        private Gtk.CheckButton checkLinked;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Pinta.PosterizeDialog
            this.Name = "Pinta.PosterizeDialog";
            this.Title = Mono.Unix.Catalog.GetString("Posterize");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Internal child Pinta.PosterizeDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hscalespinRed = new Pinta.HScaleSpinButtonWidget();
            this.hscalespinRed.Events = ((Gdk.EventMask)(256));
            this.hscalespinRed.Name = "hscalespinRed";
            this.hscalespinRed.Label = "Red";
            this.hscalespinRed.DefaultValue = 16;
            this.hscalespinRed.MaximumValue = 64;
            this.hscalespinRed.MinimumValue = 2;
            this.hscalespinRed.DigitsValue = 0;
            this.hscalespinRed.IncrementValue = 0;
            this.hscalespinRed.Value = 0;
            this.vbox2.Add(this.hscalespinRed);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.hscalespinRed]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hscalespinGreen = new Pinta.HScaleSpinButtonWidget();
            this.hscalespinGreen.Events = ((Gdk.EventMask)(256));
            this.hscalespinGreen.Name = "hscalespinGreen";
            this.hscalespinGreen.Label = "Green";
            this.hscalespinGreen.DefaultValue = 16;
            this.hscalespinGreen.MaximumValue = 64;
            this.hscalespinGreen.MinimumValue = 2;
            this.hscalespinGreen.DigitsValue = 0;
            this.hscalespinGreen.IncrementValue = 0;
            this.hscalespinGreen.Value = 0;
            this.vbox2.Add(this.hscalespinGreen);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.hscalespinGreen]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hscalespinBlue = new Pinta.HScaleSpinButtonWidget();
            this.hscalespinBlue.Events = ((Gdk.EventMask)(256));
            this.hscalespinBlue.Name = "hscalespinBlue";
            this.hscalespinBlue.Label = "Blue";
            this.hscalespinBlue.DefaultValue = 16;
            this.hscalespinBlue.MaximumValue = 64;
            this.hscalespinBlue.MinimumValue = 2;
            this.hscalespinBlue.DigitsValue = 0;
            this.hscalespinBlue.IncrementValue = 0;
            this.hscalespinBlue.Value = 0;
            this.vbox2.Add(this.hscalespinBlue);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.hscalespinBlue]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w5.Position = 0;
            w5.Expand = false;
            w5.Fill = false;
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.checkLinked = new Gtk.CheckButton();
            this.checkLinked.CanFocus = true;
            this.checkLinked.Name = "checkLinked";
            this.checkLinked.Label = Mono.Unix.Catalog.GetString("Linked");
            this.checkLinked.Active = true;
            this.checkLinked.DrawIndicator = true;
            this.checkLinked.UseUnderline = true;
            w1.Add(this.checkLinked);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(w1[this.checkLinked]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            // Internal child Pinta.PosterizeDialog.ActionArea
            Gtk.HButtonBox w7 = this.ActionArea;
            w7.Name = "dialog1_ActionArea";
            w7.Spacing = 10;
            w7.BorderWidth = ((uint)(5));
            w7.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w8 = ((Gtk.ButtonBox.ButtonBoxChild)(w7[this.buttonCancel]));
            w8.Expand = false;
            w8.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w9 = ((Gtk.ButtonBox.ButtonBoxChild)(w7[this.buttonOk]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
