
// This file has been generated by the GUI designer. Do not modify.
namespace Pinta
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action EditAction;

		private global::Gtk.Action ViewAction;

		private global::Gtk.Action ImageAction;

		private global::Gtk.Action LayersAction;

		private global::Gtk.Action AdjustmentsAction;

		private global::Gtk.Action EffectsAction;

		private global::Gtk.Action WindowAction;

		private global::Gtk.Action HelpAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.Toolbar tooltoolbar;

		private global::Gtk.HBox hbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox3;

		private global::Pinta.ColorPaletteWidget colorpalettewidget1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Toolbar toolbox1;

		private global::Gtk.Toolbar toolbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Pinta.Gui.Widgets.PintaCanvas drawingarea1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label1;

		private global::Pinta.LayersListWidget layerslistwidget1;

		private global::Gtk.Toolbar toolbar4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView history_treeview;

		private global::Gtk.Toolbar toolbar2;

		private global::Gtk.Statusbar statusbar1;

		private global::Gtk.Label label5;

		private global::Gtk.Label CursorPositionLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Pinta.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.HideIfEmpty = false;
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
			this.EditAction.HideIfEmpty = false;
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.EditAction, null);
			this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
			this.ViewAction.HideIfEmpty = false;
			this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
			w1.Add (this.ViewAction, null);
			this.ImageAction = new global::Gtk.Action ("ImageAction", global::Mono.Unix.Catalog.GetString ("Image"), null, null);
			this.ImageAction.HideIfEmpty = false;
			this.ImageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Image");
			w1.Add (this.ImageAction, null);
			this.LayersAction = new global::Gtk.Action ("LayersAction", global::Mono.Unix.Catalog.GetString ("Layers"), null, null);
			this.LayersAction.HideIfEmpty = false;
			this.LayersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Layers");
			w1.Add (this.LayersAction, null);
			this.AdjustmentsAction = new global::Gtk.Action ("AdjustmentsAction", global::Mono.Unix.Catalog.GetString ("Adjustments"), null, null);
			this.AdjustmentsAction.HideIfEmpty = false;
			this.AdjustmentsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Adjustments");
			w1.Add (this.AdjustmentsAction, "<Control>a");
			this.EffectsAction = new global::Gtk.Action ("EffectsAction", global::Mono.Unix.Catalog.GetString ("Effects"), null, null);
			this.EffectsAction.HideIfEmpty = false;
			this.EffectsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Effects");
			w1.Add (this.EffectsAction, null);
			this.WindowAction = new global::Gtk.Action ("WindowAction", global::Mono.Unix.Catalog.GetString ("Window"), null, null);
			this.WindowAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Window");
			this.WindowAction.Visible = false;
			w1.Add (this.WindowAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.HideIfEmpty = false;
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Pinta.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Pinta!");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.AllowShrink = true;
			this.DefaultWidth = 1100;
			this.DefaultHeight = 750;
			// Container child Pinta.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'/><menu name='EditAction' action='EditAction'/><menu name='ViewAction' action='ViewAction'/><menu name='ImageAction' action='ImageAction'/><menu name='LayersAction' action='LayersAction'/><menu name='AdjustmentsAction' action='AdjustmentsAction'/><menu name='EffectsAction' action='EffectsAction'/><menu name='WindowAction' action='WindowAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar1\'/></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbar1.IconSize = ((global::Gtk.IconSize)(2));
			this.vbox1.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'tooltoolbar\'/></ui>");
			this.tooltoolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tooltoolbar")));
			this.tooltoolbar.HeightRequest = 28;
			this.tooltoolbar.Name = "tooltoolbar";
			this.tooltoolbar.ShowArrow = false;
			this.tooltoolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.tooltoolbar.IconSize = ((global::Gtk.IconSize)(2));
			this.vbox1.Add (this.tooltoolbar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.tooltoolbar]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			// Container child vbox3.Gtk.Box+BoxChild
			this.colorpalettewidget1 = new global::Pinta.ColorPaletteWidget ();
			this.colorpalettewidget1.Name = "colorpalettewidget1";
			this.vbox3.Add (this.colorpalettewidget1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.colorpalettewidget1]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			// Container child hbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbox1\'/></ui>");
			this.toolbox1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbox1")));
			this.toolbox1.Name = "toolbox1";
			this.toolbox1.Orientation = ((global::Gtk.Orientation)(1));
			this.toolbox1.ShowArrow = false;
			this.toolbox1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbox1.IconSize = ((global::Gtk.IconSize)(2));
			this.hbox3.Add (this.toolbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.toolbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbox2\'/></ui>");
			this.toolbox2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbox2")));
			this.toolbox2.Name = "toolbox2";
			this.toolbox2.Orientation = ((global::Gtk.Orientation)(1));
			this.toolbox2.ShowArrow = false;
			this.toolbox2.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbox2.IconSize = ((global::Gtk.IconSize)(2));
			this.hbox3.Add (this.toolbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.toolbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(3));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w10 = new global::Gtk.Viewport ();
			w10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.drawingarea1 = new global::Pinta.Gui.Widgets.PintaCanvas ();
			this.drawingarea1.CanDefault = true;
			this.drawingarea1.CanFocus = true;
			this.drawingarea1.Events = ((global::Gdk.EventMask)(16134));
			this.drawingarea1.Name = "drawingarea1";
			w10.Add (this.drawingarea1);
			this.GtkScrolledWindow.Add (w10);
			this.hbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow]));
			w13.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Layers:");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.layerslistwidget1 = new global::Pinta.LayersListWidget ();
			this.layerslistwidget1.Name = "layerslistwidget1";
			this.vbox2.Add (this.layerslistwidget1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.layerslistwidget1]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar4\'/></ui>");
			this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar4")));
			this.toolbar4.Name = "toolbar4";
			this.toolbar4.ShowArrow = false;
			this.toolbar4.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbar4.IconSize = ((global::Gtk.IconSize)(1));
			this.vbox2.Add (this.toolbar4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.toolbar4]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.history_treeview = new global::Gtk.TreeView ();
			this.history_treeview.CanFocus = true;
			this.history_treeview.Name = "history_treeview";
			this.GtkScrolledWindow1.Add (this.history_treeview);
			this.vbox2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
			w18.Position = 3;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name=\'toolbar2\'/></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			this.toolbar2.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbar2.IconSize = ((global::Gtk.IconSize)(1));
			this.vbox2.Add (this.toolbar2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.toolbar2]));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.hbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
			w21.Position = 0;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w22.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString (" Paintbrush: Left click to draw with primary color, right click to draw with seco" + "ndary color");
			this.label5.Justify = ((global::Gtk.Justification)(3));
			this.label5.SingleLineMode = true;
			this.statusbar1.Add (this.label5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.label5]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child statusbar1.Gtk.Box+BoxChild
			this.CursorPositionLabel = new global::Gtk.Label ();
			this.CursorPositionLabel.Name = "CursorPositionLabel";
			this.CursorPositionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0, 0");
			this.statusbar1.Add (this.CursorPositionLabel);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.CursorPositionLabel]));
			w24.Position = 3;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.drawingarea1.HasDefault = true;
			this.Show ();
			this.drawingarea1.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDrawingarea1MotionNotifyEvent);
		}
	}
}
