// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Pinta.Gui.Widgets {
    
    
    public partial class PointPickerWidget {
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.HBox hbox2;
        
        private Pinta.Gui.Widgets.PointPickerGraphic pointpickergraphic1;
        
        private Gtk.Table table1;
        
        private Gtk.Button button1;
        
        private Gtk.Button button2;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.SpinButton spinX;
        
        private Gtk.SpinButton spinY;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Pinta.Gui.Widgets.PointPickerWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "Pinta.Gui.Widgets.PointPickerWidget";
            // Container child Pinta.Gui.Widgets.PointPickerWidget.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label = new Gtk.Label();
            this.label.Name = "label";
            this.label.LabelProp = Mono.Unix.Catalog.GetString("label");
            this.hbox1.Add(this.label);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.label]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.hbox1.Add(this.hseparator1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.hseparator1]));
            w2.Position = 1;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.pointpickergraphic1 = new Pinta.Gui.Widgets.PointPickerGraphic();
            this.pointpickergraphic1.Name = "pointpickergraphic1";
            this.hbox2.Add(this.pointpickergraphic1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox2[this.pointpickergraphic1]));
            w4.Position = 0;
            w4.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.button1 = new Gtk.Button();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseUnderline = true;
            // Container child button1.Gtk.Container+ContainerChild
            Gtk.Alignment w5 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w6 = new Gtk.HBox();
            w6.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w7 = new Gtk.Image();
            w7.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-back", Gtk.IconSize.Menu, 16);
            w6.Add(w7);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w9 = new Gtk.Label();
            w6.Add(w9);
            w5.Add(w6);
            this.button1.Add(w5);
            this.table1.Add(this.button1);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.button1]));
            w13.LeftAttach = ((uint)(2));
            w13.RightAttach = ((uint)(3));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.button2 = new Gtk.Button();
            this.button2.CanFocus = true;
            this.button2.Name = "button2";
            this.button2.UseUnderline = true;
            // Container child button2.Gtk.Container+ContainerChild
            Gtk.Alignment w14 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w15 = new Gtk.HBox();
            w15.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w16 = new Gtk.Image();
            w16.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-back", Gtk.IconSize.Menu, 16);
            w15.Add(w16);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w18 = new Gtk.Label();
            w15.Add(w18);
            w14.Add(w15);
            this.button2.Add(w14);
            this.table1.Add(this.button2);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table1[this.button2]));
            w22.TopAttach = ((uint)(1));
            w22.BottomAttach = ((uint)(2));
            w22.LeftAttach = ((uint)(2));
            w22.RightAttach = ((uint)(3));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("X:");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w23.XOptions = ((Gtk.AttachOptions)(4));
            w23.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Y:");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w24.TopAttach = ((uint)(1));
            w24.BottomAttach = ((uint)(2));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.spinX = new Gtk.SpinButton(0, 100, 1);
            this.spinX.CanFocus = true;
            this.spinX.Name = "spinX";
            this.spinX.Adjustment.PageIncrement = 10;
            this.spinX.ClimbRate = 1;
            this.spinX.Numeric = true;
            this.table1.Add(this.spinX);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table1[this.spinX]));
            w25.LeftAttach = ((uint)(1));
            w25.RightAttach = ((uint)(2));
            w25.XOptions = ((Gtk.AttachOptions)(4));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.spinY = new Gtk.SpinButton(0, 100, 1);
            this.spinY.CanFocus = true;
            this.spinY.Name = "spinY";
            this.spinY.Adjustment.PageIncrement = 10;
            this.spinY.ClimbRate = 1;
            this.spinY.Numeric = true;
            this.table1.Add(this.spinY);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table1[this.spinY]));
            w26.TopAttach = ((uint)(1));
            w26.BottomAttach = ((uint)(2));
            w26.LeftAttach = ((uint)(1));
            w26.RightAttach = ((uint)(2));
            w26.XOptions = ((Gtk.AttachOptions)(4));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            this.hbox2.Add(this.table1);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.hbox2[this.table1]));
            w27.Position = 1;
            w27.Expand = false;
            w27.Fill = false;
            this.vbox1.Add(this.hbox2);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
            w28.Position = 1;
            w28.Expand = false;
            w28.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
