
// This file has been generated by the GUI designer. Do not modify.
namespace Pinta.Gui.Widgets
{
	public partial class ColorPanelWidget
	{
		private global::Gtk.EventBox eventbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Pinta.Gui.Widgets.ColorPanelWidget
			global::Stetic.BinContainer.Attach (this);
			this.HeightRequest = 24;
			this.Name = "Pinta.Gui.Widgets.ColorPanelWidget";
			// Container child Pinta.Gui.Widgets.ColorPanelWidget.Gtk.Container+ContainerChild
			this.eventbox = new global::Gtk.EventBox ();
			this.eventbox.Events = ((global::Gdk.EventMask)(256));
			this.eventbox.Name = "eventbox";
			this.eventbox.VisibleWindow = false;
			this.Add (this.eventbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
