using System;

namespace Pinta.Core;

/// <summary>
/// Encapsulates an <see cref="int" /> value
/// to be used as a seed in effects whose algorithms
/// have a degree of randomness
/// </summary>
public readonly struct RandomSeed
{
	public readonly int Value { get; }
	public RandomSeed (int value)
	{
		// Note: these range checks correspond to
		// the range of values generated by Random.Next()
		if (value < 0) throw new ArgumentOutOfRangeException (nameof (value));
		if (value == int.MaxValue) throw new ArgumentOutOfRangeException (nameof (value));

		Value = value;
	}
	public override readonly bool Equals (object? obj)
	{
		if (obj is not RandomSeed other) return false;
		return Value == other.Value;
	}
	public override readonly int GetHashCode () => Value.GetHashCode ();
	public static bool operator == (RandomSeed left, RandomSeed right) => left.Equals (right);
	public static bool operator != (RandomSeed left, RandomSeed right) => !left.Equals (right);
}
